# Generated by Django 5.1.2 on 2024-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
